name: Deploy to Gitee Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: yin-xuhang/food-showcase
          branch: main
          directory: /
          https: true
